import type { Category, Place, BWEvent } from '@/types';

function photo(kw: string, seed: number, w = 800, h = 540): string {
  return `https://loremflickr.com/${w}/${h}/${kw}?lock=${seed}`;
}

export const CATEGORIES: Record<string, Category> = {
  parks:     { tint: '#3f7d57', soft: '#e8f1ec', label: { en: 'Parks & outdoors',   ru: 'Парки и природа' } },
  cafes:     { tint: '#b06a3b', soft: '#f6ece2', label: { en: 'Cafés & restaurants', ru: 'Кафе и рестораны' } },
  museums:   { tint: '#5b58a6', soft: '#ecebf5', label: { en: 'Museums & culture',   ru: 'Музеи и культура' } },
  landmarks: { tint: '#005ea5', soft: '#e6f2fb', label: { en: 'Landmarks',           ru: 'Достопримечательности' } },
  nightlife: { tint: '#7b4a86', soft: '#f1e9f3', label: { en: 'Bars & nightlife',    ru: 'Бары и ночная жизнь' } },
  shopping:  { tint: '#2f7d80', soft: '#e4f0f0', label: { en: 'Shopping & markets',  ru: 'Шопинг и базары' } },
};
export const CATEGORY_ORDER = ['parks', 'cafes', 'museums', 'landmarks', 'nightlife', 'shopping'];

export const EVENT_CATEGORIES: Record<string, Category> = {
  music:      { tint: '#b3434f', soft: '#f6e7e9', label: { en: 'Live music',   ru: 'Живая музыка' } },
  festival:   { tint: '#c97a1e', soft: '#f8eede', label: { en: 'Festivals',    ru: 'Фестивали' } },
  theatre:    { tint: '#7b4a86', soft: '#f1e9f3', label: { en: 'Theatre',      ru: 'Театр' } },
  sport:      { tint: '#2f7d80', soft: '#e4f0f0', label: { en: 'Sport',        ru: 'Спорт' } },
  film:       { tint: '#4a5aa0', soft: '#e9ebf6', label: { en: 'Film',         ru: 'Кино' } },
  exhibition: { tint: '#5b58a6', soft: '#ecebf5', label: { en: 'Exhibitions',  ru: 'Выставки' } },
};
export const EVENT_CATEGORY_ORDER = ['music', 'festival', 'theatre', 'sport', 'film', 'exhibition'];

export const PLACES: Place[] = [
  { id: 'oak-park', type: 'place', cat: 'parks', rating: 4.7, reviews: 2140, dist: 0.4, price: 0,
    photo: photo('park,trees,alley', 21), lat: 42.8767, lng: 74.6092,
    openUntil: { en: 'Open · until 23:00', ru: 'Открыто · до 23:00' }, open: true,
    name: { en: 'Oak Park', ru: 'Дубовый парк' },
    desc: { en: 'The city\'s oldest green space — shaded alleys, open-air sculptures and the Erkindik gallery fence.',
            ru: 'Старейший парк города — тенистые аллеи, скульптуры под открытым небом и галерея на ограде Эркиндик.' } },
  { id: 'panfilov', type: 'place', cat: 'parks', rating: 4.4, reviews: 980, dist: 0.9, price: 0,
    photo: photo('ferris,wheel,park', 32), lat: 42.8800, lng: 74.6010,
    openUntil: { en: 'Open · 24 hours', ru: 'Открыто · круглосуточно' }, open: true,
    name: { en: 'Panfilov Park', ru: 'Парк Панфилова' },
    desc: { en: 'Retro funfair rides, a Ferris wheel and ice-cream kiosks — a local family favourite since Soviet times.',
            ru: 'Ретро-аттракционы, колесо обозрения и киоски с мороженым — любимое место семей с советских времён.' } },
  { id: 'botanical', type: 'place', cat: 'parks', rating: 4.5, reviews: 610, dist: 6.2, price: 1,
    photo: photo('botanical,garden,roses', 14), lat: 42.8169, lng: 74.6231,
    openUntil: { en: 'Open · until 18:00', ru: 'Открыто · до 18:00' }, open: true,
    name: { en: 'Gareev Botanical Garden', ru: 'Ботанический сад им. Гареева' },
    desc: { en: 'The largest botanical garden in Central Asia — arboretum, rose terraces and quiet gravel paths.',
            ru: 'Крупнейший ботанический сад Центральной Азии — дендрарий, розарии и тихие гравийные дорожки.' } },
  { id: 'sierra', type: 'place', cat: 'cafes', rating: 4.6, reviews: 1530, dist: 0.6, price: 2,
    photo: photo('coffee,cafe,latte', 51), lat: 42.8748, lng: 74.5952,
    openUntil: { en: 'Open · until 22:00', ru: 'Открыто · до 22:00' }, open: true,
    name: { en: 'Sierra Coffee', ru: 'Sierra Coffee' },
    desc: { en: 'Bishkek\'s home-grown specialty roaster. Flat whites, walnut cake and reliably fast Wi-Fi.',
            ru: 'Местная сеть спешелти-кофе. Флэт-уайт, ореховый торт и стабильно быстрый Wi-Fi.' } },
  { id: 'frunze-rest', type: 'place', cat: 'cafes', rating: 4.5, reviews: 870, dist: 1.1, price: 2,
    photo: photo('restaurant,terrace,dinner', 63), lat: 42.8761, lng: 74.5841,
    openUntil: { en: 'Open · until 00:00', ru: 'Открыто · до 00:00' }, open: true,
    name: { en: 'Frunze Restaurant', ru: 'Ресторан «Фрунзе»' },
    desc: { en: 'Kyrgyz and European plates on a leafy terrace — try the beshbarmak or lagman.',
            ru: 'Кыргызская и европейская кухня на зелёной террасе — попробуйте бешбармак или лагман.' } },
  { id: 'navat', type: 'place', cat: 'cafes', rating: 4.6, reviews: 3200, dist: 3.0, price: 2,
    photo: photo('restaurant,interior,table', 77), lat: 42.8471, lng: 74.5991,
    openUntil: { en: 'Open · until 00:00', ru: 'Открыто · до 00:00' }, open: true,
    name: { en: 'Navat', ru: 'Нават' },
    desc: { en: 'National cuisine in a richly decorated yurt-style hall. Pots of herbal tea and warm boorsok.',
            ru: 'Национальная кухня в богато украшенном зале в стиле юрты. Чайники травяного чая и тёплый боорсок.' } },
  { id: 'history-museum', type: 'place', cat: 'museums', rating: 4.3, reviews: 1190, dist: 0.1, price: 1,
    photo: photo('museum,facade,building', 8), lat: 42.8772, lng: 74.6040,
    openUntil: { en: 'Closed · opens 09:00', ru: 'Закрыто · откроется в 09:00' }, open: false,
    name: { en: 'State Historical Museum', ru: 'Государственный исторический музей' },
    desc: { en: 'Recently restored museum on Ala-Too Square covering nomadic heritage to the modern republic.',
            ru: 'Недавно отреставрированный музей на площади Ала-Тоо — от кочевого наследия до современной республики.' } },
  { id: 'fine-arts', type: 'place', cat: 'museums', rating: 4.5, reviews: 540, dist: 1.4, price: 1,
    photo: photo('art,gallery,painting', 19), lat: 42.8731, lng: 74.6131,
    openUntil: { en: 'Open · until 18:00', ru: 'Открыто · до 18:00' }, open: true,
    name: { en: 'Museum of Fine Arts', ru: 'Музей изобразительных искусств' },
    desc: { en: 'Kyrgyz felt art, Soviet-era painting and rotating contemporary shows in a calm marble hall.',
            ru: 'Кыргызское войлочное искусство, живопись советской эпохи и сменные современные выставки.' } },
  { id: 'frunze-house', type: 'place', cat: 'museums', rating: 4.1, reviews: 330, dist: 0.8, price: 1,
    photo: photo('old,house,wooden', 41), lat: 42.8742, lng: 74.5949,
    openUntil: { en: 'Closed · opens 10:00', ru: 'Закрыто · откроется в 10:00' }, open: false,
    name: { en: 'Frunze House-Museum', ru: 'Дом-музей Фрунзе' },
    desc: { en: 'A preserved cottage encased in a monumental hall — a curious slice of early-Soviet memory.',
            ru: 'Сохранённая изба внутри монументального зала — любопытный фрагмент ранней советской памяти.' } },
  { id: 'ala-too', type: 'place', cat: 'landmarks', rating: 4.7, reviews: 5400, dist: 0.0, price: 0,
    photo: photo('square,monument,city', 29), lat: 42.8766, lng: 74.6037,
    openUntil: { en: 'Open · 24 hours', ru: 'Открыто · круглосуточно' }, open: true,
    name: { en: 'Ala-Too Square', ru: 'Площадь Ала-Тоо' },
    desc: { en: 'The ceremonial heart of the city — the Manas statue, hourly guard change and giant flagpole.',
            ru: 'Церемониальное сердце города — статуя Манаса, смена караула и гигантский флагшток.' } },
  { id: 'victory', type: 'place', cat: 'landmarks', rating: 4.6, reviews: 1870, dist: 1.3, price: 0,
    photo: photo('monument,memorial,arch', 36), lat: 42.8699, lng: 74.6189,
    openUntil: { en: 'Open · 24 hours', ru: 'Открыто · круглосуточно' }, open: true,
    name: { en: 'Victory Square', ru: 'Площадь Победы' },
    desc: { en: 'Three granite arches form a yurt frame over an eternal flame — striking at dusk.',
            ru: 'Три гранитные арки образуют каркас юрты над вечным огнём — особенно красиво на закате.' } },
  { id: 'philharmonic', type: 'place', cat: 'landmarks', rating: 4.5, reviews: 760, dist: 1.0, price: 0,
    photo: photo('concert,hall,monument', 44), lat: 42.8757, lng: 74.5868,
    openUntil: { en: 'Open · until 20:00', ru: 'Открыто · до 20:00' }, open: true,
    name: { en: 'National Philharmonic', ru: 'Национальная филармония' },
    desc: { en: 'The towering Manas monument fronts the concert hall — komuz recitals most evenings.',
            ru: 'Перед концертным залом возвышается монумент Манаса — по вечерам концерты комуза.' } },
  { id: 'save-ales', type: 'place', cat: 'nightlife', rating: 4.6, reviews: 920, dist: 0.7, price: 2,
    photo: photo('pub,beer,craft', 57), lat: 42.8741, lng: 74.5981,
    openUntil: { en: 'Open · until 02:00', ru: 'Открыто · до 02:00' }, open: true,
    name: { en: 'Save the Ales', ru: 'Save the Ales' },
    desc: { en: 'Craft-beer pub with a rotating Central Asian tap list and unfussy, generous burgers.',
            ru: 'Крафтовый паб со сменным списком центральноазиатского пива и щедрыми бургерами.' } },
  { id: 'pinta', type: 'place', cat: 'nightlife', rating: 4.3, reviews: 1340, dist: 0.9, price: 2,
    photo: photo('bar,pub,interior', 66), lat: 42.8762, lng: 74.5931,
    openUntil: { en: 'Open · until 01:00', ru: 'Открыто · до 01:00' }, open: true,
    name: { en: 'Pinta Pub', ru: 'Pinta Pub' },
    desc: { en: 'A long-running expat-and-local pub. Live football, dart boards and a buzzy summer courtyard.',
            ru: 'Старейший паб для экспатов и местных. Трансляции футбола, дартс и шумный летний дворик.' } },
  { id: 'osh-bazaar', type: 'place', cat: 'shopping', rating: 4.4, reviews: 4100, dist: 2.6, price: 1,
    photo: photo('market,bazaar,spices', 72), lat: 42.8731, lng: 74.5642,
    openUntil: { en: 'Open · until 19:00', ru: 'Открыто · до 19:00' }, open: true,
    name: { en: 'Osh Bazaar', ru: 'Ошский базар' },
    desc: { en: 'The classic city market — spice mountains, dried fruit, felt slippers and the smell of fresh non.',
            ru: 'Классический городской базар — горы специй, сухофрукты, войлочные тапки и запах свежего нона.' } },
  { id: 'bishkek-park', type: 'place', cat: 'shopping', rating: 4.5, reviews: 2750, dist: 1.0, price: 2,
    photo: photo('shopping,mall,interior', 83), lat: 42.8690, lng: 74.5871,
    openUntil: { en: 'Open · until 22:00', ru: 'Открыто · до 22:00' }, open: true,
    name: { en: 'Bishkek Park Mall', ru: 'ТРЦ Bishkek Park' },
    desc: { en: 'Modern mall with international brands, a top-floor food court and a cinema — good rainy-day plan.',
            ru: 'Современный ТРЦ с международными брендами, фуд-кортом и кинотеатром — план на дождливый день.' } },
  { id: 'dordoi', type: 'place', cat: 'shopping', rating: 4.2, reviews: 3300, dist: 7.5, price: 1,
    photo: photo('market,goods,stall', 91), lat: 42.9231, lng: 74.6392,
    openUntil: { en: 'Closed · opens 07:00', ru: 'Закрыто · откроется в 07:00' }, open: false,
    name: { en: 'Dordoi Bazaar', ru: 'Базар Дордой' },
    desc: { en: 'One of the largest markets in Central Asia — endless container alleys; go early and haggle.',
            ru: 'Один из крупнейших рынков Центральной Азии — бесконечные ряды контейнеров; приходите рано и торгуйтесь.' } },
];

export const EVENTS: BWEvent[] = [
  { id: 'ev-komuz', type: 'event', cat: 'music', rating: 4.8, reviews: 210, dist: 1.0, price: 1,
    photo: photo('concert,stage,lights', 102), lat: 42.8757, lng: 74.5868,
    when: { en: 'Fri 5 Jun · 19:00', ru: 'Пт 5 июн · 19:00' },
    venue: { en: 'National Philharmonic', ru: 'Национальная филармония' },
    name: { en: 'Komuz & Symphony Night', ru: 'Вечер комуза и симфонии' },
    desc: { en: 'Kyrgyz folk instruments meet a full orchestra — an annual sell-out at the Philharmonic.',
            ru: 'Кыргызские народные инструменты в сопровождении оркестра — ежегодный аншлаг в филармонии.' } },
  { id: 'ev-jazz', type: 'event', cat: 'music', rating: 4.6, reviews: 95, dist: 0.7, price: 2,
    photo: photo('jazz,band,music', 111), lat: 42.8741, lng: 74.5981,
    when: { en: 'Sat 6 Jun · 21:00', ru: 'Сб 6 июн · 21:00' },
    venue: { en: 'Save the Ales', ru: 'Save the Ales' },
    name: { en: 'Late Jazz Sessions', ru: 'Ночные джаз-сейшены' },
    desc: { en: 'A rotating quartet plays standards and improv till late. Arrive early for a seat near the stage.',
            ru: 'Квартет играет стандарты и импровизации до позднего вечера. Приходите заранее за местом у сцены.' } },
  { id: 'ev-food', type: 'event', cat: 'festival', rating: 4.7, reviews: 540, dist: 0.4, price: 0,
    photo: photo('food,festival,street', 120), lat: 42.8767, lng: 74.6092,
    when: { en: 'Sun 7 Jun · 12:00', ru: 'Вс 7 июн · 12:00' },
    venue: { en: 'Oak Park', ru: 'Дубовый парк' },
    name: { en: 'Bishkek Street Food Fair', ru: 'Ярмарка уличной еды' },
    desc: { en: 'Dozens of stalls from samsa to Korean-Kyrgyz fusion, with live music on the park lawn.',
            ru: 'Десятки прилавков от самсы до корейско-кыргызского фьюжна и живая музыка на газоне парка.' } },
  { id: 'ev-nomad', type: 'event', cat: 'festival', rating: 4.9, reviews: 380, dist: 6.2, price: 1,
    photo: photo('horse,nomad,festival', 129), lat: 42.8169, lng: 74.6231,
    when: { en: 'Sat 13 Jun · 10:00', ru: 'Сб 13 июн · 10:00' },
    venue: { en: 'Hippodrome', ru: 'Ипподром' },
    name: { en: 'Nomad Games Showcase', ru: 'Игры кочевников' },
    desc: { en: 'Kok-boru, eagle hunting and yurt-building demos — a high-energy taste of nomadic sport.',
            ru: 'Кок-бору, охота с беркутом и сборка юрты — энергичное знакомство с кочевым спортом.' } },
  { id: 'ev-theatre', type: 'event', cat: 'theatre', rating: 4.4, reviews: 130, dist: 0.9, price: 1,
    photo: photo('theatre,stage,curtain', 138), lat: 42.8758, lng: 74.6010,
    when: { en: 'Thu 11 Jun · 18:30', ru: 'Чт 11 июн · 18:30' },
    venue: { en: 'Russian Drama Theatre', ru: 'Русский драматический театр' },
    name: { en: 'Manas: A Stage Epic', ru: 'Манас: сценический эпос' },
    desc: { en: 'A bold, modern staging of the national epic with live throat-singing and projection design.',
            ru: 'Смелая современная постановка национального эпоса с горловым пением и проекциями.' } },
  { id: 'ev-film', type: 'event', cat: 'film', rating: 4.5, reviews: 220, dist: 1.0, price: 1,
    photo: photo('cinema,film,screen', 147), lat: 42.8690, lng: 74.5871,
    when: { en: 'Wed 10 Jun · 20:00', ru: 'Ср 10 июн · 20:00' },
    venue: { en: 'Bishkek Park Cinema', ru: 'Кинотеатр Bishkek Park' },
    name: { en: 'Central Asian Film Week', ru: 'Неделя кино Центральной Азии' },
    desc: { en: 'A curated run of new regional cinema with English and Russian subtitles and director Q&As.',
            ru: 'Программа нового регионального кино с английскими и русскими субтитрами и встречами с режиссёрами.' } },
  { id: 'ev-exhib', type: 'event', cat: 'exhibition', rating: 4.6, reviews: 175, dist: 1.4, price: 1,
    photo: photo('art,exhibition,gallery', 156), lat: 42.8731, lng: 74.6131,
    when: { en: 'Daily · until 28 Jun', ru: 'Ежедневно · до 28 июн' },
    venue: { en: 'Museum of Fine Arts', ru: 'Музей изобразительных искусств' },
    name: { en: 'Felt & Form', ru: 'Войлок и форма' },
    desc: { en: 'Contemporary Kyrgyz artists reimagine traditional felt-making across a three-room show.',
            ru: 'Современные кыргызские художники переосмысляют традиционный войлок в трёх залах.' } },
  { id: 'ev-run', type: 'event', cat: 'sport', rating: 4.7, reviews: 410, dist: 0.0, price: 1,
    photo: photo('marathon,running,race', 165), lat: 42.8766, lng: 74.6037,
    when: { en: 'Sun 14 Jun · 07:00', ru: 'Вс 14 июн · 07:00' },
    venue: { en: 'Ala-Too Square (start)', ru: 'Площадь Ала-Тоо (старт)' },
    name: { en: 'Bishkek City Run', ru: 'Городской забег Бишкека' },
    desc: { en: '5K, 10K and half-marathon routes through the centre, closing on the square for the finish.',
            ru: 'Маршруты 5 км, 10 км и полумарафон по центру с финишем на площади.' } },
  { id: 'ev-electronic', type: 'event', cat: 'music', rating: 4.3, reviews: 88, dist: 0.9, price: 2,
    photo: photo('nightclub,party,dj', 174), lat: 42.8762, lng: 74.5931,
    when: { en: 'Sat 6 Jun · 23:00', ru: 'Сб 6 июн · 23:00' },
    venue: { en: 'Pinta Courtyard', ru: 'Двор Pinta' },
    name: { en: 'Open-Air Electronic Night', ru: 'Электронная ночь под открытым небом' },
    desc: { en: 'Local and visiting DJs on an open-air courtyard stage — the unofficial start of summer.',
            ru: 'Местные и приглашённые диджеи на сцене под открытым небом — неофициальное начало лета.' } },
  { id: 'ev-craft', type: 'event', cat: 'festival', rating: 4.5, reviews: 260, dist: 2.6, price: 0,
    photo: photo('craft,market,handmade', 183), lat: 42.8731, lng: 74.5642,
    when: { en: 'Sat–Sun 13–14 Jun', ru: 'Сб–Вс 13–14 июн' },
    venue: { en: 'Osh Bazaar Square', ru: 'Площадь Ошского базара' },
    name: { en: 'Artisans\' Craft Fair', ru: 'Ярмарка ремёсел' },
    desc: { en: 'Felt, silver, leather and ceramics straight from the makers — bargaining encouraged.',
            ru: 'Войлок, серебро, кожа и керамика напрямую от мастеров — торг приветствуется.' } },
];

export const CENTER: [number, number] = [42.8760, 74.5960];

export function getCatMap(type: 'place' | 'event') {
  return type === 'event' ? EVENT_CATEGORIES : CATEGORIES;
}
export function getCatOrder(type: 'place' | 'event') {
  return type === 'event' ? EVENT_CATEGORY_ORDER : CATEGORY_ORDER;
}
